import type { Icon } from "@phosphor-icons/react";
import {
  Folder,
  FolderOpen,
  FolderSimple,
  House,
  Tray,
  Archive,
  Bookmark,
  BookmarkSimple,
  Star,
  Heart,
  Flag,
  Tag,
  Hash,
  Files,
  File,
  Bell,
  Gift,
  Briefcase,
  Buildings,
  Calendar,
  CalendarDot,
  Clock,
  Gavel,
  Notebook,
  PenNib,
  PencilSimple,
  ChartBar,
  Printer,
  Code,
  Terminal,
  Bug,
  Package,
  Cube,
  Database,
  Cloud,
  CloudArrowUp,
  Cpu,
  Network,
  GithubLogo,
  Palette,
  PaintBrush,
  Ruler,
  Image,
  Camera,
  Aperture,
  SquaresFour,
  Eyedropper,
  MusicNote,
  MusicNotes,
  Microphone,
  Headphones,
  FilmSlate,
  FilmReel,
  Play,
  VinylRecord,
  Guitar,
  SpeakerHigh,
  Monitor,
  Television,
  Users,
  UserCircle,
  ChatCircle,
  Phone,
  Envelope,
  Megaphone,
  SlackLogo,
  DiscordLogo,
  XLogo,
  YoutubeLogo,
  SpotifyLogo,
  Airplane,
  Car,
  CarSimple,
  Bicycle,
  Train,
  Boat,
  Sailboat,
  Taxi,
  MapTrifold,
  Compass,
  Globe,
  Mountains,
  Tree,
  TreePalm,
  TreeEvergreen,
  Tent,
  Anchor,
  Binoculars,
  Feather,
  Sun,
  SunDim,
  Moon,
  CloudRain,
  CloudLightning,
  CloudSnow,
  Snowflake,
  Umbrella,
  Coffee,
  BowlFood,
  Hamburger,
  Pizza,
  Cookie,
  Wine,
  GraduationCap,
  Book,
  BookOpen,
  Books,
  Brain,
  Lightbulb,
  Atom,
  Flask,
  Microscope,
  ShoppingBag,
  ShoppingCart,
  Storefront,
  Handbag,
  Ticket,
  GameController,
  Joystick,
  Sword,
  PuzzlePiece,
  SoccerBall,
  Football,
  Volleyball,
  Barbell,
  PersonSimpleRun,
  Heartbeat,
  Pill,
  FirstAidKit,
  Stethoscope,
  Hospital,
  Bandaids,
  Horse,
  Dog,
  Cat,
  Bird,
  Butterfly,
  Fish,
  Rabbit,
  Smiley,
  SmileySad,
  SmileyWink,
  Lock,
  Key,
  Shield,
  Eye,
  Crown,
  Flame,
  Sparkle,
  CheckCircle,
  Diamond,
  Lightning,
  Gear,
  Wrench,
  Hammer,
  Lifebuoy,
  // New Additions
  Bank,
  CreditCard,
  Coins,
  Receipt,
  Wallet,
  Money,
  TrendUp,
  TrendDown,
  Flower,
  FlowerLotus,
  Leaf,
  Plant,
  Cactus,
  Waves,
  Fire,
  Park,
  CookingPot,
  ForkKnife,
  Carrot,
  Egg,
  IceCream,
  Presentation,
  ProjectorScreen,
  Desktop,
  Student,
  Certificate,
  Trophy,
  Medal,
  Lamp,
  Watch,
  MagnifyingGlass,
  Funnel,
  Trash,
  Paperclip,
  Suitcase,
  SuitcaseRolling,
  MapPin,
  NavigationArrow,
  HeartBreak,
  Infinity,
  PlusCircle,
  Article,
  Newspaper,
  Quotes,
  PintGlass,
  Sneaker,
  HandHeart,
  TShirt,
} from "@phosphor-icons/react";

export type IconCategory =
  | "General"
  | "Work"
  | "Finance"
  | "Development"
  | "Design"
  | "Media"
  | "Social"
  | "Travel"
  | "Nature"
  | "Weather"
  | "Food"
  | "Learning"
  | "Shopping"
  | "Games"
  | "Sports"
  | "Health"
  | "Wellness"
  | "Animals"
  | "Symbols"
  | "Objects";

export interface IconDef {
  name: string;
  Component: Icon;
  category: IconCategory;
  keywords: string[];
}

// Curated catalog. Keywords are lowercase terms used by the picker search.
export const ICONS: IconDef[] = [
  // General
  { name: "Folder", Component: Folder, category: "General", keywords: ["folder", "directory"] },
  { name: "FolderOpen", Component: FolderOpen, category: "General", keywords: ["folder", "open"] },
  { name: "FolderSimple", Component: FolderSimple, category: "General", keywords: ["folder", "simple"] },
  { name: "House", Component: House, category: "General", keywords: ["home", "house"] },
  { name: "Tray", Component: Tray, category: "General", keywords: ["inbox", "tray", "incoming"] },
  { name: "Archive", Component: Archive, category: "General", keywords: ["archive", "box", "storage"] },
  { name: "Bookmark", Component: Bookmark, category: "General", keywords: ["bookmark", "save"] },
  { name: "BookmarkSimple", Component: BookmarkSimple, category: "General", keywords: ["bookmark"] },
  { name: "Star", Component: Star, category: "General", keywords: ["star", "favorite"] },
  { name: "Heart", Component: Heart, category: "General", keywords: ["heart", "love", "favorite"] },
  { name: "Flag", Component: Flag, category: "General", keywords: ["flag", "important"] },
  { name: "Tag", Component: Tag, category: "General", keywords: ["tag", "label"] },
  { name: "Hash", Component: Hash, category: "General", keywords: ["hash", "hashtag", "number"] },
  { name: "Files", Component: Files, category: "General", keywords: ["files", "documents"] },
  { name: "File", Component: File, category: "General", keywords: ["file", "document"] },
  { name: "Article", Component: Article, category: "General", keywords: ["article", "reading", "news"] },
  { name: "Newspaper", Component: Newspaper, category: "General", keywords: ["news", "newspaper", "press"] },
  { name: "Bell", Component: Bell, category: "General", keywords: ["bell", "notification"] },
  { name: "Gift", Component: Gift, category: "General", keywords: ["gift", "present"] },

  // Work
  { name: "Briefcase", Component: Briefcase, category: "Work", keywords: ["briefcase", "work", "job"] },
  { name: "Buildings", Component: Buildings, category: "Work", keywords: ["office", "buildings", "company"] },
  { name: "Calendar", Component: Calendar, category: "Work", keywords: ["calendar", "date"] },
  { name: "CalendarDot", Component: CalendarDot, category: "Work", keywords: ["calendar", "event"] },
  { name: "Clock", Component: Clock, category: "Work", keywords: ["clock", "time"] },
  { name: "Gavel", Component: Gavel, category: "Work", keywords: ["gavel", "legal", "law"] },
  { name: "Notebook", Component: Notebook, category: "Work", keywords: ["notebook", "notes"] },
  { name: "PenNib", Component: PenNib, category: "Work", keywords: ["pen", "writing"] },
  { name: "PencilSimple", Component: PencilSimple, category: "Work", keywords: ["pencil", "edit", "writing"] },
  { name: "ChartBar", Component: ChartBar, category: "Work", keywords: ["chart", "analytics", "data"] },
  { name: "Presentation", Component: Presentation, category: "Work", keywords: ["presentation", "slides", "meeting"] },
  { name: "ProjectorScreen", Component: ProjectorScreen, category: "Work", keywords: ["projector", "meeting"] },
  { name: "Printer", Component: Printer, category: "Work", keywords: ["printer", "print"] },

  // Finance
  { name: "Bank", Component: Bank, category: "Finance", keywords: ["bank", "finance", "money"] },
  { name: "CreditCard", Component: CreditCard, category: "Finance", keywords: ["credit card", "payment", "money"] },
  { name: "Coins", Component: Coins, category: "Finance", keywords: ["coins", "money", "finance"] },
  { name: "Receipt", Component: Receipt, category: "Finance", keywords: ["receipt", "bill", "invoice"] },
  { name: "Wallet", Component: Wallet, category: "Finance", keywords: ["wallet", "money"] },
  { name: "Money", Component: Money, category: "Finance", keywords: ["money", "cash", "finance"] },
  { name: "TrendUp", Component: TrendUp, category: "Finance", keywords: ["trend", "up", "stocks", "growth"] },
  { name: "TrendDown", Component: TrendDown, category: "Finance", keywords: ["trend", "down", "stocks", "loss"] },

  // Development
  { name: "Code", Component: Code, category: "Development", keywords: ["code", "programming", "development"] },
  { name: "Terminal", Component: Terminal, category: "Development", keywords: ["terminal", "console", "shell"] },
  { name: "Bug", Component: Bug, category: "Development", keywords: ["bug", "issue", "error"] },
  { name: "Package", Component: Package, category: "Development", keywords: ["package", "box", "library"] },
  { name: "Cube", Component: Cube, category: "Development", keywords: ["cube", "3d", "module"] },
  { name: "Database", Component: Database, category: "Development", keywords: ["database", "data", "storage"] },
  { name: "Cloud", Component: Cloud, category: "Development", keywords: ["cloud", "server"] },
  { name: "CloudArrowUp", Component: CloudArrowUp, category: "Development", keywords: ["cloud", "upload"] },
  { name: "Cpu", Component: Cpu, category: "Development", keywords: ["cpu", "chip", "processor", "hardware"] },
  { name: "Network", Component: Network, category: "Development", keywords: ["network", "connections"] },
  { name: "GithubLogo", Component: GithubLogo, category: "Development", keywords: ["github", "git", "repo"] },

  // Design
  { name: "Palette", Component: Palette, category: "Design", keywords: ["palette", "color", "design"] },
  { name: "PaintBrush", Component: PaintBrush, category: "Design", keywords: ["paint", "brush", "design"] },
  { name: "Ruler", Component: Ruler, category: "Design", keywords: ["ruler", "measure", "design"] },
  { name: "Image", Component: Image, category: "Design", keywords: ["image", "picture", "photo"] },
  { name: "Camera", Component: Camera, category: "Design", keywords: ["camera", "photography"] },
  { name: "Aperture", Component: Aperture, category: "Design", keywords: ["aperture", "lens", "camera"] },
  { name: "SquaresFour", Component: SquaresFour, category: "Design", keywords: ["grid", "squares", "layout"] },
  { name: "Eyedropper", Component: Eyedropper, category: "Design", keywords: ["eyedropper", "color", "picker"] },

  // Media
  { name: "MusicNote", Component: MusicNote, category: "Media", keywords: ["music", "note", "song"] },
  { name: "MusicNotes", Component: MusicNotes, category: "Media", keywords: ["music", "notes", "song"] },
  { name: "Microphone", Component: Microphone, category: "Media", keywords: ["microphone", "mic", "audio", "podcast"] },
  { name: "Headphones", Component: Headphones, category: "Media", keywords: ["headphones", "audio"] },
  { name: "FilmSlate", Component: FilmSlate, category: "Media", keywords: ["film", "movie", "clapperboard"] },
  { name: "FilmReel", Component: FilmReel, category: "Media", keywords: ["film", "reel", "movie"] },
  { name: "Play", Component: Play, category: "Media", keywords: ["play", "video"] },
  { name: "VinylRecord", Component: VinylRecord, category: "Media", keywords: ["vinyl", "record", "music"] },
  { name: "Guitar", Component: Guitar, category: "Media", keywords: ["guitar", "music", "instrument"] },
  { name: "SpeakerHigh", Component: SpeakerHigh, category: "Media", keywords: ["speaker", "volume", "audio"] },
  { name: "Monitor", Component: Monitor, category: "Media", keywords: ["monitor", "screen", "display"] },
  { name: "Television", Component: Television, category: "Media", keywords: ["television", "tv", "video"] },

  // Social
  { name: "Users", Component: Users, category: "Social", keywords: ["users", "people", "team"] },
  { name: "UserCircle", Component: UserCircle, category: "Social", keywords: ["user", "profile", "account"] },
  { name: "ChatCircle", Component: ChatCircle, category: "Social", keywords: ["chat", "message", "conversation"] },
  { name: "Phone", Component: Phone, category: "Social", keywords: ["phone", "call"] },
  { name: "Envelope", Component: Envelope, category: "Social", keywords: ["email", "mail", "envelope"] },
  { name: "Megaphone", Component: Megaphone, category: "Social", keywords: ["megaphone", "announcement", "marketing"] },
  { name: "SlackLogo", Component: SlackLogo, category: "Social", keywords: ["slack", "chat"] },
  { name: "DiscordLogo", Component: DiscordLogo, category: "Social", keywords: ["discord", "chat"] },
  { name: "XLogo", Component: XLogo, category: "Social", keywords: ["x", "twitter", "social"] },
  { name: "YoutubeLogo", Component: YoutubeLogo, category: "Social", keywords: ["youtube", "video"] },
  { name: "SpotifyLogo", Component: SpotifyLogo, category: "Social", keywords: ["spotify", "music"] },

  // Travel
  { name: "Airplane", Component: Airplane, category: "Travel", keywords: ["airplane", "plane", "flight", "travel"] },
  { name: "Suitcase", Component: Suitcase, category: "Travel", keywords: ["suitcase", "travel", "bag"] },
  { name: "SuitcaseRolling", Component: SuitcaseRolling, category: "Travel", keywords: ["suitcase", "travel", "luggage"] },
  { name: "MapPin", Component: MapPin, category: "Travel", keywords: ["map", "location", "pin"] },
  { name: "NavigationArrow", Component: NavigationArrow, category: "Travel", keywords: ["navigation", "gps", "direction"] },
  { name: "Car", Component: Car, category: "Travel", keywords: ["car", "vehicle", "drive"] },
  { name: "CarSimple", Component: CarSimple, category: "Travel", keywords: ["car", "simple"] },
  { name: "Bicycle", Component: Bicycle, category: "Travel", keywords: ["bicycle", "bike", "cycling"] },
  { name: "Train", Component: Train, category: "Travel", keywords: ["train", "rail"] },
  { name: "Boat", Component: Boat, category: "Travel", keywords: ["boat", "ship"] },
  { name: "Sailboat", Component: Sailboat, category: "Travel", keywords: ["sailboat", "sailing", "boat"] },
  { name: "Taxi", Component: Taxi, category: "Travel", keywords: ["taxi", "cab", "travel"] },
  { name: "MapTrifold", Component: MapTrifold, category: "Travel", keywords: ["map", "travel", "directions"] },
  { name: "Compass", Component: Compass, category: "Travel", keywords: ["compass", "direction"] },
  { name: "Globe", Component: Globe, category: "Travel", keywords: ["globe", "world", "earth"] },

  // Nature
  { name: "Mountains", Component: Mountains, category: "Nature", keywords: ["mountains", "hiking", "outdoor"] },
  { name: "Tree", Component: Tree, category: "Nature", keywords: ["tree", "nature"] },
  { name: "TreePalm", Component: TreePalm, category: "Nature", keywords: ["palm", "tree", "tropical", "beach"] },
  { name: "TreeEvergreen", Component: TreeEvergreen, category: "Nature", keywords: ["evergreen", "tree", "forest"] },
  { name: "Flower", Component: Flower, category: "Nature", keywords: ["flower", "nature", "garden"] },
  { name: "FlowerLotus", Component: FlowerLotus, category: "Nature", keywords: ["lotus", "flower", "yoga", "meditation"] },
  { name: "Leaf", Component: Leaf, category: "Nature", keywords: ["leaf", "nature", "plant"] },
  { name: "Plant", Component: Plant, category: "Nature", keywords: ["plant", "nature", "garden"] },
  { name: "Cactus", Component: Cactus, category: "Nature", keywords: ["cactus", "nature", "desert"] },
  { name: "Waves", Component: Waves, category: "Nature", keywords: ["waves", "ocean", "sea", "beach"] },
  { name: "Fire", Component: Fire, category: "Nature", keywords: ["fire", "flame", "hot"] },
  { name: "Park", Component: Park, category: "Nature", keywords: ["park", "nature", "outdoor"] },
  { name: "Tent", Component: Tent, category: "Nature", keywords: ["tent", "camping", "outdoor"] },
  { name: "Anchor", Component: Anchor, category: "Nature", keywords: ["anchor", "boat", "nautical"] },

  // Weather
  { name: "Sun", Component: Sun, category: "Weather", keywords: ["sun", "sunny", "day"] },
  { name: "SunDim", Component: SunDim, category: "Weather", keywords: ["sun", "dim"] },
  { name: "Moon", Component: Moon, category: "Weather", keywords: ["moon", "night"] },
  { name: "CloudRain", Component: CloudRain, category: "Weather", keywords: ["rain", "cloud", "weather"] },
  { name: "CloudLightning", Component: CloudLightning, category: "Weather", keywords: ["lightning", "storm", "weather"] },
  { name: "CloudSnow", Component: CloudSnow, category: "Weather", keywords: ["snow", "cloud", "weather"] },
  { name: "Snowflake", Component: Snowflake, category: "Weather", keywords: ["snow", "snowflake", "cold"] },
  { name: "Umbrella", Component: Umbrella, category: "Weather", keywords: ["umbrella", "rain"] },

  // Food
  { name: "Coffee", Component: Coffee, category: "Food", keywords: ["coffee", "drink", "cafe"] },
  { name: "BowlFood", Component: BowlFood, category: "Food", keywords: ["food", "bowl", "meal"] },
  { name: "CookingPot", Component: CookingPot, category: "Food", keywords: ["cook", "pot", "cooking", "recipe"] },
  { name: "ForkKnife", Component: ForkKnife, category: "Food", keywords: ["eat", "restaurant", "food", "dining"] },
  { name: "Carrot", Component: Carrot, category: "Food", keywords: ["carrot", "vegetable", "food", "healthy"] },
  { name: "Egg", Component: Egg, category: "Food", keywords: ["egg", "food", "breakfast"] },
  { name: "Hamburger", Component: Hamburger, category: "Food", keywords: ["burger", "hamburger", "food"] },
  { name: "Pizza", Component: Pizza, category: "Food", keywords: ["pizza", "food"] },
  { name: "Cookie", Component: Cookie, category: "Food", keywords: ["cookie", "snack"] },
  { name: "IceCream", Component: IceCream, category: "Food", keywords: ["ice cream", "dessert", "sweet"] },
  { name: "Wine", Component: Wine, category: "Food", keywords: ["wine", "drink", "alcohol"] },
  { name: "PintGlass", Component: PintGlass, category: "Food", keywords: ["beer", "pint", "drink"] },

  // Learning
  { name: "GraduationCap", Component: GraduationCap, category: "Learning", keywords: ["graduation", "school", "education"] },
  { name: "Student", Component: Student, category: "Learning", keywords: ["student", "learning", "education"] },
  { name: "Certificate", Component: Certificate, category: "Learning", keywords: ["certificate", "award", "education"] },
  { name: "Book", Component: Book, category: "Learning", keywords: ["book", "reading"] },
  { name: "BookOpen", Component: BookOpen, category: "Learning", keywords: ["book", "open", "reading"] },
  { name: "Books", Component: Books, category: "Learning", keywords: ["books", "library", "reading"] },
  { name: "Brain", Component: Brain, category: "Learning", keywords: ["brain", "psychology", "learning", "mind"] },
  { name: "Lightbulb", Component: Lightbulb, category: "Learning", keywords: ["lightbulb", "idea", "inspiration"] },
  { name: "Atom", Component: Atom, category: "Learning", keywords: ["atom", "science", "physics"] },
  { name: "Flask", Component: Flask, category: "Learning", keywords: ["flask", "science", "chemistry", "lab"] },
  { name: "Microscope", Component: Microscope, category: "Learning", keywords: ["microscope", "science", "lab"] },

  // Shopping
  { name: "ShoppingBag", Component: ShoppingBag, category: "Shopping", keywords: ["shopping", "bag", "commerce"] },
  { name: "ShoppingCart", Component: ShoppingCart, category: "Shopping", keywords: ["shopping", "cart", "commerce"] },
  { name: "Storefront", Component: Storefront, category: "Shopping", keywords: ["storefront", "shop", "store"] },
  { name: "Handbag", Component: Handbag, category: "Shopping", keywords: ["handbag", "purse", "fashion"] },
  { name: "TShirt", Component: TShirt, category: "Shopping", keywords: ["clothing", "shirt", "fashion"] },
  { name: "Ticket", Component: Ticket, category: "Shopping", keywords: ["ticket", "event"] },

  // Games
  { name: "GameController", Component: GameController, category: "Games", keywords: ["game", "controller", "gaming"] },
  { name: "Joystick", Component: Joystick, category: "Games", keywords: ["joystick", "arcade", "retro", "gaming"] },
  { name: "Sword", Component: Sword, category: "Games", keywords: ["sword", "rpg", "weapon"] },
  { name: "PuzzlePiece", Component: PuzzlePiece, category: "Games", keywords: ["puzzle", "piece", "game"] },

  // Sports
  { name: "SoccerBall", Component: SoccerBall, category: "Sports", keywords: ["soccer", "football", "ball"] },
  { name: "Football", Component: Football, category: "Sports", keywords: ["football", "ball"] },
  { name: "Volleyball", Component: Volleyball, category: "Sports", keywords: ["volleyball", "ball"] },
  { name: "Barbell", Component: Barbell, category: "Sports", keywords: ["barbell", "gym", "weights", "fitness"] },
  { name: "Trophy", Component: Trophy, category: "Sports", keywords: ["trophy", "winner", "award"] },
  { name: "Medal", Component: Medal, category: "Sports", keywords: ["medal", "award", "winner"] },
  { name: "PersonSimpleRun", Component: PersonSimpleRun, category: "Sports", keywords: ["run", "running", "jog", "fitness"] },

  // Health
  { name: "Heartbeat", Component: Heartbeat, category: "Health", keywords: ["heart", "pulse", "health"] },
  { name: "Pill", Component: Pill, category: "Health", keywords: ["pill", "medicine", "health"] },
  { name: "FirstAidKit", Component: FirstAidKit, category: "Health", keywords: ["first aid", "kit", "medical"] },
  { name: "Stethoscope", Component: Stethoscope, category: "Health", keywords: ["stethoscope", "doctor", "medical"] },
  { name: "Hospital", Component: Hospital, category: "Health", keywords: ["hospital", "medical"] },
  { name: "Bandaids", Component: Bandaids, category: "Health", keywords: ["bandaids", "medical"] },

  // Wellness
  { name: "HandHeart", Component: HandHeart, category: "Wellness", keywords: ["wellness", "care", "health"] },
  { name: "Sneaker", Component: Sneaker, category: "Wellness", keywords: ["shoes", "fitness", "running"] },

  // Animals
  { name: "Horse", Component: Horse, category: "Animals", keywords: ["horse", "animal"] },
  { name: "Dog", Component: Dog, category: "Animals", keywords: ["dog", "animal", "pet"] },
  { name: "Cat", Component: Cat, category: "Animals", keywords: ["cat", "animal", "pet"] },
  { name: "Bird", Component: Bird, category: "Animals", keywords: ["bird", "animal"] },
  { name: "Butterfly", Component: Butterfly, category: "Animals", keywords: ["butterfly", "animal", "insect"] },
  { name: "Fish", Component: Fish, category: "Animals", keywords: ["fish", "animal"] },
  { name: "Rabbit", Component: Rabbit, category: "Animals", keywords: ["rabbit", "bunny", "animal"] },
  { name: "Smiley", Component: Smiley, category: "Animals", keywords: ["smiley", "happy", "face"] },
  { name: "SmileySad", Component: SmileySad, category: "Animals", keywords: ["sad", "face"] },
  { name: "SmileyWink", Component: SmileyWink, category: "Animals", keywords: ["wink", "face"] },

  // Objects
  { name: "Lamp", Component: Lamp, category: "Objects", keywords: ["lamp", "light", "home"] },
  { name: "Watch", Component: Watch, category: "Objects", keywords: ["watch", "time", "accessory"] },
  { name: "Binoculars", Component: Binoculars, category: "Objects", keywords: ["binoculars", "travel", "view"] },
  { name: "MagnifyingGlass", Component: MagnifyingGlass, category: "Objects", keywords: ["search", "find", "zoom"] },
  { name: "Funnel", Component: Funnel, category: "Objects", keywords: ["filter", "funnel"] },
  { name: "Trash", Component: Trash, category: "Objects", keywords: ["delete", "trash", "remove"] },
  { name: "Paperclip", Component: Paperclip, category: "Objects", keywords: ["attach", "paperclip", "file"] },
  { name: "Quotes", Component: Quotes, category: "Objects", keywords: ["quote", "text"] },

  // Symbols / misc
  { name: "Lock", Component: Lock, category: "Symbols", keywords: ["lock", "secure", "password"] },
  { name: "Key", Component: Key, category: "Symbols", keywords: ["key", "password", "secret"] },
  { name: "Shield", Component: Shield, category: "Symbols", keywords: ["shield", "security", "protection"] },
  { name: "Eye", Component: Eye, category: "Symbols", keywords: ["eye", "view", "see"] },
  { name: "Crown", Component: Crown, category: "Symbols", keywords: ["crown", "king", "premium"] },
  { name: "Flame", Component: Flame, category: "Symbols", keywords: ["flame", "fire", "hot", "trending"] },
  { name: "Sparkle", Component: Sparkle, category: "Symbols", keywords: ["sparkle", "new", "ai", "magic"] },
  { name: "CheckCircle", Component: CheckCircle, category: "Symbols", keywords: ["check", "done", "complete"] },
  { name: "Diamond", Component: Diamond, category: "Symbols", keywords: ["diamond", "premium", "valuable"] },
  { name: "Lightning", Component: Lightning, category: "Symbols", keywords: ["lightning", "fast", "quick", "zap"] },
  { name: "HeartBreak", Component: HeartBreak, category: "Symbols", keywords: ["heart", "break", "sad"] },
  { name: "Infinity", Component: Infinity, category: "Symbols", keywords: ["infinity", "forever", "math"] },
  { name: "PlusCircle", Component: PlusCircle, category: "Symbols", keywords: ["add", "plus", "new"] },
  { name: "Gear", Component: Gear, category: "Symbols", keywords: ["gear", "settings", "config"] },
  { name: "Wrench", Component: Wrench, category: "Symbols", keywords: ["wrench", "tools", "fix"] },
  { name: "Hammer", Component: Hammer, category: "Symbols", keywords: ["hammer", "tools", "build"] },
  { name: "Lifebuoy", Component: Lifebuoy, category: "Symbols", keywords: ["lifebuoy", "help", "support"] },
];

// Fast lookup by name; falls back to the default folder icon.
const BY_NAME = new Map<string, Icon>(ICONS.map((i) => [i.name, i.Component]));

export const DefaultCollectionIcon: Icon = Folder;

export function iconComponentByName(name: string | null | undefined): Icon {
  if (!name) return DefaultCollectionIcon;
  return BY_NAME.get(name) ?? DefaultCollectionIcon;
}

export const ICON_CATEGORIES: IconCategory[] = [
  "General",
  "Work",
  "Finance",
  "Development",
  "Design",
  "Media",
  "Social",
  "Travel",
  "Nature",
  "Weather",
  "Food",
  "Learning",
  "Shopping",
  "Games",
  "Sports",
  "Health",
  "Wellness",
  "Animals",
  "Symbols",
  "Objects",
];

