import type { LucideIcon } from "lucide-react";
import {
  Aperture,
  Anchor,
  Archive,
  Atom,
  BadgeCheck,
  Bandage,
  Banknote,
  BarChart3,
  Beer,
  Bell,
  Binoculars,
  Bird,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Brain,
  BriefcaseBusiness,
  BriefcaseMedical,
  Building2,
  Bug,
  Camera,
  CalendarDays,
  Car,
  CarTaxiFront,
  Carrot,
  Cat,
  CheckCircle,
  Clapperboard,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  CloudUpload,
  Clock3,
  Code2,
  Coffee,
  Coins,
  Compass,
  CookingPot,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  Disc3,
  Dog,
  Dumbbell,
  Egg,
  Eye,
  Feather,
  File,
  Film,
  Filter,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderClosed,
  FolderOpen,
  ForkKnife,
  Frown,
  Gamepad2,
  Gavel,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Grid2x2,
  Guitar,
  Hammer,
  HandHeart,
  Hamburger,
  Hash,
  Headphones,
  Heart,
  HeartCrack,
  HeartPulse,
  Hospital,
  House,
  IceCreamCone,
  Image,
  Inbox,
  Infinity,
  Joystick,
  KeyRound,
  Landmark,
  Lamp,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Lock,
  Luggage,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Music,
  Music2,
  Navigation,
  Network,
  Newspaper,
  NotebookPen,
  Package,
  Paintbrush,
  Palette,
  Paperclip,
  Pencil,
  PenTool,
  Phone,
  PiggyBank,
  Pill,
  Pipette,
  Pizza,
  Plane,
  Play,
  PlusCircle,
  Printer,
  Projector,
  Puzzle,
  Quote,
  Rabbit,
  Receipt,
  Ruler,
  Sailboat,
  Search,
  Settings,
  Shield,
  Shirt,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  SportShoe,
  Star,
  Stethoscope,
  Store,
  Sun,
  SunDim,
  Sword,
  Tag,
  Tent,
  Terminal,
  Ticket,
  Train,
  TrendingDown,
  TrendingUp,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Trash2,
  Trophy,
  Tv,
  Umbrella,
  Users,
  Volume2,
  Volleyball,
  Wallet,
  Watch,
  Waves,
  Wine,
  Wrench,
  Zap,
  Bike,
  CircleUser,
  Files,
  Cookie,
  Medal,
  Map as MapIcon,
} from "lucide-react";

export type IconCategory =
  | "General"
  | "Work"
  | "Finance"
  | "Development"
  | "Design"
  | "Media"
  | "Social"
  | "Travel"
  | "Nature"
  | "Weather"
  | "Food"
  | "Learning"
  | "Shopping"
  | "Games"
  | "Sports"
  | "Health"
  | "Wellness"
  | "Animals"
  | "Symbols"
  | "Objects";

export interface IconDef {
  name: string;
  Component: LucideIcon;
  category: IconCategory;
  keywords: string[];
}

const icon = (
  name: string,
  Component: LucideIcon,
  category: IconCategory,
  keywords: string[],
): IconDef => ({ name, Component, category, keywords });

// Curated Lucide catalog. Keywords are lowercase terms used by the picker search.
export const ICONS: IconDef[] = [
  // General
  icon("Folder", Folder, "General", ["folder", "directory"]),
  icon("FolderClosed", FolderClosed, "General", ["folder", "closed"]),
  icon("FolderOpen", FolderOpen, "General", ["folder", "open"]),
  icon("House", House, "General", ["home", "house"]),
  icon("Inbox", Inbox, "General", ["inbox", "tray", "incoming"]),
  icon("Archive", Archive, "General", ["archive", "storage", "box"]),
  icon("Bookmark", Bookmark, "General", ["bookmark", "save"]),
  icon("Star", Star, "General", ["favorite", "star"]),
  icon("Heart", Heart, "General", ["heart", "favorite", "love"]),
  icon("Flag", Flag, "General", ["flag", "important"]),
  icon("Tag", Tag, "General", ["tag", "label"]),
  icon("Hash", Hash, "General", ["hash", "number", "hashtag"]),
  icon("Files", Files, "General", ["files", "documents"]),
  icon("File", File, "General", ["file", "document"]),
  icon("Newspaper", Newspaper, "General", ["article", "reading", "news", "press"]),
  icon("Bell", Bell, "General", ["bell", "notification"]),
  icon("Gift", Gift, "General", ["gift", "present"]),

  // Work
  icon("BriefcaseBusiness", BriefcaseBusiness, "Work", ["work", "briefcase", "business", "job"]),
  icon("Building2", Building2, "Work", ["building", "office", "company"]),
  icon("CalendarDays", CalendarDays, "Work", ["calendar", "date", "schedule"]),
  icon("Clock3", Clock3, "Work", ["clock", "time"]),
  icon("Gavel", Gavel, "Work", ["law", "legal", "gavel"]),
  icon("NotebookPen", NotebookPen, "Work", ["notes", "notebook", "writing"]),
  icon("PenTool", PenTool, "Work", ["pen", "nib", "tool"]),
  icon("Pencil", Pencil, "Work", ["pencil", "edit", "write"]),
  icon("BarChart3", BarChart3, "Work", ["chart", "graph", "analytics"]),
  icon("Presentation", Projector, "Work", ["presentation", "slides", "pitch"]),
  icon("Projector", Projector, "Work", ["projector", "presentation"]),
  icon("Printer", Printer, "Work", ["printer", "print"]),

  // Finance
  icon("Landmark", Landmark, "Finance", ["bank", "finance", "money", "building"]),
  icon("CreditCard", CreditCard, "Finance", ["credit", "payment", "card"]),
  icon("Coins", Coins, "Finance", ["coins", "money", "cash"]),
  icon("Receipt", Receipt, "Finance", ["receipt", "expense", "bill"]),
  icon("Wallet", Wallet, "Finance", ["wallet", "money"]),
  icon("Banknote", Banknote, "Finance", ["banknote", "cash", "money"]),
  icon("PiggyBank", PiggyBank, "Finance", ["piggy", "bank", "savings"]),
  icon("TrendingUp", TrendingUp, "Finance", ["trend", "up", "growth"]),
  icon("TrendingDown", TrendingDown, "Finance", ["trend", "down", "decline"]),

  // Development
  icon("Code2", Code2, "Development", ["code", "programming"]),
  icon("Terminal", Terminal, "Development", ["terminal", "shell", "cli"]),
  icon("Bug", Bug, "Development", ["bug", "issue"]),
  icon("Package", Package, "Development", ["package", "shipping", "dependency"]),
  icon("Box", Box, "Development", ["box", "cube", "package"]),
  icon("Database", Database, "Development", ["database", "data"]),
  icon("Cloud", Cloud, "Development", ["cloud", "infrastructure"]),
  icon("CloudUpload", CloudUpload, "Development", ["cloud", "upload", "deploy"]),
  icon("Cpu", Cpu, "Development", ["cpu", "chip", "compute"]),
  icon("Network", Network, "Development", ["network", "nodes"]),
  icon("GitBranch", GitBranch, "Development", ["git", "github", "version control"]),

  // Design
  icon("Palette", Palette, "Design", ["palette", "color", "art"]),
  icon("Paintbrush", Paintbrush, "Design", ["paintbrush", "brush", "paint"]),
  icon("Ruler", Ruler, "Design", ["ruler", "measure"]),
  icon("Image", Image, "Design", ["image", "photo", "picture"]),
  icon("Camera", Camera, "Design", ["camera", "photo"]),
  icon("Aperture", Aperture, "Design", ["aperture", "lens", "camera"]),
  icon("Grid2x2", Grid2x2, "Design", ["grid", "layout", "squares"]),
  icon("Pipette", Pipette, "Design", ["pipette", "eyedropper", "color"]),

  // Media
  icon("Music", Music, "Media", ["music", "note"]),
  icon("Music2", Music2, "Media", ["music", "notes", "audio"]),
  icon("Mic", Mic, "Media", ["microphone", "podcast", "audio"]),
  icon("Headphones", Headphones, "Media", ["headphones", "audio"]),
  icon("Clapperboard", Clapperboard, "Media", ["film", "slate", "movie"]),
  icon("Film", Film, "Media", ["film", "reel", "movie"]),
  icon("Play", Play, "Media", ["play", "video", "watch"]),
  icon("Disc3", Disc3, "Media", ["record", "vinyl", "disc", "spotify"]),
  icon("Guitar", Guitar, "Media", ["guitar", "music"]),
  icon("Volume2", Volume2, "Media", ["speaker", "volume", "sound"]),
  icon("Monitor", Monitor, "Media", ["monitor", "screen", "desktop"]),
  icon("Tv", Tv, "Media", ["tv", "television"]),

  // Social
  icon("Users", Users, "Social", ["users", "group", "people"]),
  icon("CircleUser", CircleUser, "Social", ["user", "profile", "person"]),
  icon("MessageCircle", MessageCircle, "Social", ["chat", "message", "slack", "discord"]),
  icon("Phone", Phone, "Social", ["phone", "call"]),
  icon("Mail", Mail, "Social", ["mail", "email", "envelope"]),
  icon("Megaphone", Megaphone, "Social", ["megaphone", "announcement", "x", "twitter"]),
  icon("Globe", Globe, "Social", ["globe", "world", "web"]),

  // Travel
  icon("Plane", Plane, "Travel", ["plane", "flight", "travel"]),
  icon("Car", Car, "Travel", ["car", "drive"]),
  icon("Bike", Bike, "Travel", ["bike", "bicycle"]),
  icon("Train", Train, "Travel", ["train", "rail"]),
  icon("Ship", Ship, "Travel", ["ship", "boat"]),
  icon("Sailboat", Sailboat, "Travel", ["sailboat", "boat"]),
  icon("CarTaxiFront", CarTaxiFront, "Travel", ["taxi", "cab", "car"]),
  icon("Map", MapIcon, "Travel", ["map", "atlas"]),
  icon("Compass", Compass, "Travel", ["compass", "direction"]),
  icon("MapPin", MapPin, "Travel", ["map pin", "location", "place"]),
  icon("Navigation", Navigation, "Travel", ["navigation", "arrow", "direction"]),
  icon("Luggage", Luggage, "Travel", ["luggage", "suitcase", "travel"]),

  // Nature
  icon("Mountain", Mountain, "Nature", ["mountain", "landscape"]),
  icon("TreeDeciduous", TreeDeciduous, "Nature", ["tree", "nature"]),
  icon("TreePine", TreePine, "Nature", ["evergreen", "pine", "tree"]),
  icon("TreePalm", TreePalm, "Nature", ["palm", "tree", "tropical"]),
  icon("Trees", Trees, "Nature", ["trees", "forest", "park"]),
  icon("Tent", Tent, "Nature", ["tent", "camping"]),
  icon("Anchor", Anchor, "Nature", ["anchor", "marine"]),
  icon("Binoculars", Binoculars, "Nature", ["binoculars", "birding", "explore"]),
  icon("Feather", Feather, "Nature", ["feather", "light"]),
  icon("Flower2", Flower2, "Nature", ["flower", "bloom"]),
  icon("Leaf", Leaf, "Nature", ["leaf", "plant", "green"]),
  icon("Waves", Waves, "Nature", ["waves", "water", "ocean"]),

  // Weather
  icon("Sun", Sun, "Weather", ["sun", "day"]),
  icon("SunDim", SunDim, "Weather", ["sun dim", "sunset", "soft"]),
  icon("Moon", Moon, "Weather", ["moon", "night"]),
  icon("CloudRain", CloudRain, "Weather", ["cloud", "rain"]),
  icon("CloudLightning", CloudLightning, "Weather", ["cloud", "lightning", "storm"]),
  icon("CloudSnow", CloudSnow, "Weather", ["cloud", "snow"]),
  icon("Snowflake", Snowflake, "Weather", ["snowflake", "snow"]),
  icon("Umbrella", Umbrella, "Weather", ["umbrella", "rain"]),

  // Food
  icon("Coffee", Coffee, "Food", ["coffee", "drink"]),
  icon("Soup", Soup, "Food", ["soup", "bowl", "food"]),
  icon("CookingPot", CookingPot, "Food", ["pot", "cooking", "kitchen"]),
  icon("ForkKnife", ForkKnife, "Food", ["fork", "knife", "restaurant"]),
  icon("Carrot", Carrot, "Food", ["carrot", "vegetable"]),
  icon("Egg", Egg, "Food", ["egg", "breakfast"]),
  icon("Hamburger", Hamburger, "Food", ["hamburger", "burger"]),
  icon("Pizza", Pizza, "Food", ["pizza"]),
  icon("Cookie", Cookie, "Food", ["cookie", "dessert"]),
  icon("IceCreamCone", IceCreamCone, "Food", ["ice cream", "dessert"]),
  icon("Wine", Wine, "Food", ["wine", "drink"]),
  icon("Beer", Beer, "Food", ["beer", "pint", "drink"]),

  // Learning
  icon("GraduationCap", GraduationCap, "Learning", ["graduation", "school", "student"]),
  icon("Book", Book, "Learning", ["book", "read"]),
  icon("BookOpen", BookOpen, "Learning", ["book open", "reading"]),
  icon("Brain", Brain, "Learning", ["brain", "ideas", "thinking"]),
  icon("Lightbulb", Lightbulb, "Learning", ["lightbulb", "idea"]),
  icon("Atom", Atom, "Learning", ["atom", "science"]),
  icon("FlaskConical", FlaskConical, "Learning", ["flask", "science", "lab"]),
  icon("Microscope", Microscope, "Learning", ["microscope", "science"]),

  // Shopping
  icon("ShoppingBag", ShoppingBag, "Shopping", ["shopping", "bag"]),
  icon("ShoppingCart", ShoppingCart, "Shopping", ["shopping", "cart"]),
  icon("Store", Store, "Shopping", ["store", "shop", "storefront"]),
  icon("Shirt", Shirt, "Shopping", ["shirt", "fashion", "clothes"]),
  icon("Ticket", Ticket, "Shopping", ["ticket", "admission"]),

  // Games
  icon("Gamepad2", Gamepad2, "Games", ["gamepad", "controller", "gaming"]),
  icon("Joystick", Joystick, "Games", ["joystick", "arcade", "gaming"]),
  icon("Sword", Sword, "Games", ["sword", "fantasy"]),
  icon("Puzzle", Puzzle, "Games", ["puzzle", "piece"]),

  // Sports
  icon("Trophy", Trophy, "Sports", ["trophy", "winner"]),
  icon("Medal", Medal, "Sports", ["medal", "award"]),
  icon("Dumbbell", Dumbbell, "Sports", ["dumbbell", "fitness", "gym"]),
  icon("Volleyball", Volleyball, "Sports", ["volleyball", "sport", "ball"]),
  icon("SportShoe", SportShoe, "Sports", ["shoe", "sneaker", "running"]),

  // Health
  icon("HeartPulse", HeartPulse, "Health", ["heart", "pulse", "health"]),
  icon("Pill", Pill, "Health", ["pill", "medicine"]),
  icon("BriefcaseMedical", BriefcaseMedical, "Health", ["first aid", "medical", "kit"]),
  icon("Stethoscope", Stethoscope, "Health", ["stethoscope", "doctor"]),
  icon("Hospital", Hospital, "Health", ["hospital", "medical"]),
  icon("Bandage", Bandage, "Health", ["bandage", "bandaid"]),

  // Wellness
  icon("HandHeart", HandHeart, "Wellness", ["hand", "heart", "care"]),
  icon("Watch", Watch, "Wellness", ["watch", "time"]),
  icon("Smile", Smile, "Wellness", ["smile", "happy"]),
  icon("Frown", Frown, "Wellness", ["frown", "sad"]),

  // Animals
  icon("Dog", Dog, "Animals", ["dog", "pet"]),
  icon("Cat", Cat, "Animals", ["cat", "pet"]),
  icon("Bird", Bird, "Animals", ["bird", "animal"]),
  icon("Fish", Fish, "Animals", ["fish", "animal"]),
  icon("Rabbit", Rabbit, "Animals", ["rabbit", "animal"]),

  // Symbols
  icon("Lock", Lock, "Symbols", ["lock", "secure"]),
  icon("KeyRound", KeyRound, "Symbols", ["key", "password", "secret"]),
  icon("Shield", Shield, "Symbols", ["shield", "security", "protection"]),
  icon("Eye", Eye, "Symbols", ["eye", "view"]),
  icon("Crown", Crown, "Symbols", ["crown", "premium"]),
  icon("Flame", Flame, "Symbols", ["flame", "fire", "hot"]),
  icon("Sparkles", Sparkles, "Symbols", ["sparkles", "magic", "ai"]),
  icon("CheckCircle", CheckCircle, "Symbols", ["check", "complete", "done"]),
  icon("Diamond", Diamond, "Symbols", ["diamond", "premium", "valuable"]),
  icon("Zap", Zap, "Symbols", ["zap", "fast", "quick", "lightning"]),
  icon("HeartCrack", HeartCrack, "Symbols", ["heart break", "sad"]),
  icon("Infinity", Infinity, "Symbols", ["infinity", "forever"]),
  icon("PlusCircle", PlusCircle, "Symbols", ["plus", "add", "new"]),
  icon("BadgeCheck", BadgeCheck, "Symbols", ["badge", "verified", "check"]),
  icon("Settings", Settings, "Symbols", ["settings", "gear", "config"]),
  icon("Wrench", Wrench, "Symbols", ["wrench", "tools"]),
  icon("Hammer", Hammer, "Symbols", ["hammer", "tools", "build"]),
  icon("LifeBuoy", LifeBuoy, "Symbols", ["lifebuoy", "support", "help"]),

  // Objects
  icon("Lamp", Lamp, "Objects", ["lamp", "light"]),
  icon("Search", Search, "Objects", ["search", "magnifying glass"]),
  icon("Filter", Filter, "Objects", ["filter", "funnel"]),
  icon("Trash2", Trash2, "Objects", ["trash", "delete", "remove"]),
  icon("Paperclip", Paperclip, "Objects", ["paperclip", "attach"]),
  icon("Quote", Quote, "Objects", ["quote", "text", "quotes"]),
];

const ALIASES: Record<string, string> = {
  Airplane: "Plane",
  Article: "Newspaper",
  Bandaids: "Bandage",
  Bank: "Landmark",
  Bicycle: "Bike",
  Boat: "Ship",
  BookmarkSimple: "Bookmark",
  Books: "BookOpen",
  BowlFood: "Soup",
  Briefcase: "BriefcaseBusiness",
  Buildings: "Building2",
  Calendar: "CalendarDays",
  CalendarDot: "CalendarDays",
  CarSimple: "CarTaxiFront",
  ChatCircle: "MessageCircle",
  CheckCircle: "CheckCircle",
  CloudArrowUp: "CloudUpload",
  Clock: "Clock3",
  Code: "Code2",
  CookingPot: "CookingPot",
  Cube: "Box",
  Desktop: "Monitor",
  DiscordLogo: "MessageCircle",
  Envelope: "Mail",
  Eyedropper: "Pipette",
  FilmReel: "Film",
  FilmSlate: "Clapperboard",
  FirstAidKit: "BriefcaseMedical",
  Flask: "FlaskConical",
  Flower: "Flower2",
  FlowerLotus: "Flower2",
  Football: "Trophy",
  FolderSimple: "FolderClosed",
  GameController: "Gamepad2",
  Gear: "Settings",
  GithubLogo: "GitBranch",
  Handbag: "ShoppingBag",
  HeartBreak: "HeartCrack",
  Heartbeat: "HeartPulse",
  IceCream: "IceCreamCone",
  Key: "KeyRound",
  Lifebuoy: "LifeBuoy",
  Lightning: "Zap",
  MagnifyingGlass: "Search",
  MapTrifold: "Map",
  Microphone: "Mic",
  Money: "Banknote",
  Mountains: "Mountain",
  MusicNote: "Music",
  MusicNotes: "Music2",
  NavigationArrow: "Navigation",
  Newspaper: "Newspaper",
  Notebook: "NotebookPen",
  PaintBrush: "Paintbrush",
  Park: "Trees",
  PenNib: "PenTool",
  PencilSimple: "Pencil",
  PersonSimpleRun: "SportShoe",
  PintGlass: "Beer",
  PlusCircle: "PlusCircle",
  Presentation: "Presentation",
  ProjectorScreen: "Projector",
  PuzzlePiece: "Puzzle",
  Quotes: "Quote",
  SlackLogo: "MessageCircle",
  Smiley: "Smile",
  SmileySad: "Frown",
  SmileyWink: "Smile",
  Sneaker: "SportShoe",
  SoccerBall: "Volleyball",
  Sparkle: "Sparkles",
  SpeakerHigh: "Volume2",
  SpotifyLogo: "Disc3",
  SquaresFour: "Grid2x2",
  Storefront: "Store",
  Student: "GraduationCap",
  Suitcase: "Luggage",
  SuitcaseRolling: "Luggage",
  SunDim: "SunDim",
  Taxi: "CarTaxiFront",
  Television: "Tv",
  Tray: "Inbox",
  TrendDown: "TrendingDown",
  TrendUp: "TrendingUp",
  Tree: "TreeDeciduous",
  TreeEvergreen: "TreePine",
  TShirt: "Shirt",
  UserCircle: "CircleUser",
  VinylRecord: "Disc3",
  Volleyball: "Volleyball",
  XLogo: "Megaphone",
  YoutubeLogo: "Play",
  Horse: "Bird",
  Butterfly: "Bird",
  Plant: "Leaf",
  Cactus: "TreePalm",
  Fire: "Flame",
  Watch: "Watch",
};

// Fast lookup by name; falls back to the default folder icon.
const BY_NAME = new Map<string, LucideIcon>(ICONS.map((i) => [i.name, i.Component]));

export const DefaultCollectionIcon: LucideIcon = Folder;

/**
 * Returns the canonical curated icon name (PascalCase) for a stored value, or
 * null if no curated match exists. The IconPicker also supports picking from
 * the full Lucide catalog — those icons are stored as kebab-case names and
 * resolved by `isCuratedIconName` returning false + `lucide-all-icons` taking
 * over rendering.
 */
export function resolveIconName(name: string | null | undefined): string | null {
  if (!name) return null;
  if (BY_NAME.has(name)) return name;
  return ALIASES[name] ?? null;
}

/** True if `name` is in the curated catalog (or one of its legacy aliases). */
export function isCuratedIconName(name: string | null | undefined): boolean {
  return resolveIconName(name) !== null;
}

export function iconComponentByName(name: string | null | undefined): LucideIcon {
  const resolved = resolveIconName(name);
  if (!resolved) return DefaultCollectionIcon;
  return BY_NAME.get(resolved) ?? DefaultCollectionIcon;
}

export const ICON_CATEGORIES: IconCategory[] = [
  "General",
  "Work",
  "Finance",
  "Development",
  "Design",
  "Media",
  "Social",
  "Travel",
  "Nature",
  "Weather",
  "Food",
  "Learning",
  "Shopping",
  "Games",
  "Sports",
  "Health",
  "Wellness",
  "Animals",
  "Symbols",
  "Objects",
];
